#!/bin/bash
APERTIUM_PATH="/home/vmsanchez/local/bin"

cd $1

awk '{punto = index($0, "<?"); cabeza = substr($0, 1, punto-1); cola = substr($0, punto); n1 = substr(cabeza, index(cabeza, "\"")+1); name = substr(n1, 1, index(n1, "\"")-1); gsub("[?]> ", "?>\n", cola); print cola > name;}'
cd odt-content
rm -Rf ObjectReplacements
zip -q -r - . > ../output.zip
cat ../output.zip

