/*
 * Copyright 2015 Jacob Nordfalk
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 */
package apertiumview;

/**
 *
 * @author Jacob Nordfalk
 */
public class OptionsPanel extends javax.swing.JPanel {

    /** Creates new form OptionsPanel */
	public OptionsPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    envVarsTextArea = new javax.swing.JTextArea();
    ignoreStdErr = new javax.swing.JCheckBox();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    workingDirTextField = new javax.swing.JTextField();
    perferExternalEditor = new javax.swing.JCheckBox();

    envVarsTextArea.setColumns(20);
    envVarsTextArea.setRows(5);
    jScrollPane1.setViewportView(envVarsTextArea);

    ignoreStdErr.setText("<html>Ignore error messages from commands<br>\nThis will make stderr be ignored and transfer<br>\nrule tracing and warnings will not be shown");

    jLabel1.setText("<html>Working directory for external commands<br>(leave empty to use default)");

    jLabel2.setText("<html>Environment variables for external commands<br>\n(leave empty to use default)<br>\nExample: LANG=en_US.UTF-8");

    workingDirTextField.setText("jTextField1");

    perferExternalEditor.setText("Prefer external editor for editing source files");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addComponent(workingDirTextField)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(ignoreStdErr)
              .addComponent(perferExternalEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(perferExternalEditor)
        .addGap(1, 1, 1)
        .addComponent(ignoreStdErr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(workingDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

    public void setExternalProcessingOptionsEnabled(boolean b) {
        envVarsTextArea.setEnabled(b);
        ignoreStdErr.setEnabled(b);
        jLabel1.setEnabled(b);
        jLabel2.setEnabled(b);
        jScrollPane1.setEnabled(b);
        workingDirTextField.setEnabled(b);
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  javax.swing.JTextArea envVarsTextArea;
  public javax.swing.JCheckBox ignoreStdErr;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  javax.swing.JCheckBox perferExternalEditor;
  javax.swing.JTextField workingDirTextField;
  // End of variables declaration//GEN-END:variables

}
