<?php

if ($dir=="") {
   print "<option disabled='true' selected='true'>" . _("Select direction...") . "</option>";
}
print "<option value='es-ca' " . ($dir == 'es-ca' ? ' selected=true' : '') . ">" . _("Spanish") . " &rarr; " . _("Catalan") . "</option>";
print "<option value='es-ca_valencia' " . ($dir == 'es-ca_valencia' ? ' selected=true' : '') . ">" . _("Spanish") . " &rarr; " . _("Catalan (Valencian)") . "</option>";
print "<option value='ca-es' " . ($dir == 'ca-es' ? ' selected=true' : '') . ">" . _("Catalan") . " &rarr; " . _("Spanish") . "</option>";
print "<option disabled='true'></option>";
print "<option value='es-gl' " . ($dir == 'es-gl' ? ' selected=true' : '') . ">" . _("Spanish") . " &rarr; " . _("Galician") . "</option>";
print "<option value='gl-es' " . ($dir == 'gl-es' ? ' selected=true' : '') . ">" . _("Galician") . " &rarr; " . _("Spanish") . "</option>";
print "<option disabled='true'></option>";
print "<option value='es-pt' " . ($dir == 'es-pt' ? ' selected=true' : '') . ">" . _("Spanish") . " &rarr; " . _("Portuguese") . "</option>";
print "<option value='pt-es' " . ($dir == 'pt-es' ? ' selected=true' : '') . ">" . _("Portuguese") . " &rarr; " . _("Spanish") . "</option>";
print "<option value='es-pt_BR' " . ($dir == 'es-pt_BR' ? ' selected=true' : '') . ">" . _("Spanish") . " &rarr; " . _("Brazilian Portuguese") . "</option>";
print "<option disabled='true'></option>";
print "<option value='oc-ca' " . ($dir == 'oc-ca' ? ' selected=true' : '') . ">" . _("Occitan") . " &rarr; " . _("Catalan") . "</option>";
print "<option value='ca-oc' " . ($dir == 'ca-oc' ? ' selected=true' : '') . ">" . _("Catalan") . " &rarr; " . _("Occitan") . "</option>";
print "<option disabled='true'></option>";
print "<option value='oc_aran-ca' " . ($dir == 'oc_aran-ca' ? ' selected=true' : '') . ">" . _("Aranese") . " &rarr; " . _("Catalan") . "</option>";
print "<option value='ca-oc_aran' " . ($dir == 'ca-oc_aran' ? ' selected=true' : '') . ">" . _("Catalan") . " &rarr; " . _("Aranese") . "</option>";
print "<option disabled='true'></option>";
print "<option value='en-ca' " . ($dir == 'en-ca' ? ' selected=true' : '') . ">" . _("English") . " &rarr; " . _("Catalan") . "</option>";
print "<option value='ca-en' " . ($dir == 'ca-en' ? ' selected=true' : '') . ">" . _("Catalan") . " &rarr; " . _("English") . "</option>";
print "<option disabled='true'></option>";
print "<option value='fr-ca' " . ($dir == 'fr-ca' ? ' selected=true' : '') . ">" . _("French") . " &rarr; " . _("Catalan") . "</option>";
print "<option value='ca-fr' " . ($dir == 'ca-fr' ? ' selected=true' : '') . ">" . _("Catalan") . " &rarr; " . _("French") . "</option>";
print "<option disabled='true'></option>";
print "<option value='fr-es' " . ($dir == 'fr-es' ? ' selected=true' : '') . ">" . _("French") . " &rarr; " . _("Spanish") . "</option>";
print "<option value='es-fr' " . ($dir == 'es-fr' ? ' selected=true' : '') . ">" . _("Spanish") . " &rarr; " . _("French") . "</option>";
print "<option disabled='true'></option>";
//print "<option value='eo-ca' " . ($dir == 'eo-ca' ? ' selected=true' : '') . ">" . _("Esperanto") . " &rarr; " . _("Catalan") . "</option>";
print "<option value='ca-eo' " . ($dir == 'ca-eo' ? ' selected=true' : '') . ">" . _("Catalan") . " &rarr; " . _("Esperanto") . "</option>";
print "<option disabled='true'></option>";
//print "<option value='eo-es' " . ($dir == 'eo-es' ? ' selected=true' : '') . ">" . _("Esperanto") . " &rarr; " . _("Spanish") . "</option>";
print "<option value='es-eo' " . ($dir == 'es-eo' ? ' selected=true' : '') . ">" . _("Spanish") . " &rarr; " . _("Esperanto") . "</option>";
print "<option disabled='true'></option>";	    
//print "<option value='es-ro' " . ($dir == 'es-ro' ? ' selected=true' : '') . ">" . _("Spanish") . " &rarr; " . _("Romanian") . "</option>";
print "<option value='ro-es' " . ($dir == 'ro-es' ? ' selected=true' : '') . ">" . _("Romanian") . " &rarr; " . _("Spanish") . "</option>";
print "<option disabled='true'></option>";	    
print "<option value='es-en' " . ($dir == 'es-en' ? ' selected=true' : '') . ">" . _("Spanish") . " &rarr; " . _("English") . "</option>";
print "<option value='en-es' " . ($dir == 'en-es' ? ' selected=true' : '') . ">" . _("English") . " &rarr; " . _("Spanish") . "</option>";
print "<option disabled='true'></option>";	    
print "<option value='cy-en' " . ($dir == 'cy-en' ? ' selected=true' : '') . ">" . _("Welsh") . " &rarr; " . _("English") . "</option>";
print "<option disabled='true'></option>";	    
print "<option value='eu-es' " . ($dir == 'eu-es' ? ' selected=true' : '') . ">" . _("Basque") . " &rarr; " . _("Spanish") . "</option>";
print "<option disabled='true'></option>";	    
print "<option value='en-gl' " . ($dir == 'en-gl' ? ' selected=true' : '') . ">" . _("English") . " &rarr; " . _("Galician") . "</option>";
print "<option value='gl-en' " . ($dir == 'gl-en' ? ' selected=true' : '') . ">" . _("Galician") . " &rarr; " . _("English") . "</option>";
print "<option disabled='true'></option>";	    
print "<option value='en-eo' " . ($dir == 'en-eo' ? ' selected=true' : '') . ">" . _("English") . " &rarr; " . _("Esperanto") . "</option>";
print "<option value='eo-en' " . ($dir == 'eo-en' ? ' selected=true' : '') . ">" . _("Esperanto") . " &rarr; " . _("English") . "</option>";
print "<option disabled='true'></option>";	    
print "<option value='pt-ca' " . ($dir == 'pt-ca' ? ' selected=true' : '') . ">" . _("Portuguese") . " &rarr; " . _("Catalan") . "</option>";
print "<option value='ca-pt' " . ($dir == 'ca-pt' ? ' selected=true' : '') . ">" . _("Catalan") . " &rarr; " . _("Portuguese") . "</option>";
print "<option disabled='true'></option>";	    
print "<option value='br-fr' " . ($dir == 'br-fr' ? ' selected=true' : '') . ">" . _("Breton") . " &rarr; " . _("French") . "</option>";
print "<option disabled='true'></option>";	    
print "<option value='nb-nn' " . ($dir == 'nb-nn' ? ' selected=true' : '') . ">" . _("Norwegian Bokmål") . " &rarr; " . _("Norwegian Nynorsk") . "</option>";
print "<option value='nn-nb' " . ($dir == 'nn-nb' ? ' selected=true' : '') . ">" . _("Norwegian Nynorsk") . " &rarr; " . _("Norwegian Bokmål") . "</option>";
print "<option disabled='true'></option>";	    
print "<option value='sv-da' " . ($dir == 'sv-da' ? ' selected=true' : '') . ">" . _("Swedish") . " &rarr; " . _("Danish") . "</option>";
print "<option disabled='true'></option>";	    
print "<option value='es-ast' " . ($dir == 'es-ast' ? ' selected=true' : '') . ">" . _("Spanish") . " &rarr; " . _("Asturian") . "</option>";
print "<option disabled='true'></option>";	    
print "<option value='is-en' " . ($dir == 'is-en' ? ' selected=true' : '') . ">" . _("Icelandic") . " &rarr; " . _("English") . "</option>";
?>
