#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_io_InputStream;
@class java_lang_Object;
@class java_io_Writer;
@class java_lang_StringBuilder;
@class java_lang_String;
@class java_io_PrintStream;
@class java_lang_System;
@class org_apertium_lttoolbox_process_FSTProcessor;
@class java_io_StringWriter;
@class java_io_BufferedInputStream;
@class Playground;
@class StringReader2;
@class java_io_Reader;
@class java_io_FileInputStream;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface _Playground : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
- (void) __init__Playground__;
+ (void) main___java_lang_String_ARRAYTYPE :(XMLVMArray*)n1;

@end

