#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_lang_Object;
@class org_apertium_lttoolbox_LTProc;
@class Profiling;
@class java_lang_StringBuilder;
@class java_lang_String;
@class java_util_Date;
@class java_io_PrintStream;
@class java_lang_System;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface _Profiling : java_lang_Object
{
@private java_lang_String* _Profiling_dir;

}
+ (void) initialize;
- (id) init;
+ (long) _GET_now;
+ (void) _PUT_now: (long) v;
- (java_lang_String*) _GET_dir;
- (void) _PUT_dir: (java_lang_String*) v;
- (void) __init__Profiling__;
+ (void) report___java_lang_String :(java_lang_String*)n1;
+ (void) main___java_lang_String_ARRAYTYPE :(XMLVMArray*)n1;
- (void) testjavaAnalysis__;
- (void) testjavaGeneration__;
- (void) testjavaDGeneration__;
- (void) testjavaNGeneration__;
- (void) testjavaPostgeneration__;
+ (void) __clinit__Profiling;

@end

