#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_io_InputStream;
@class java_util_Properties;
@class java_io_BufferedWriter;
@class java_io_FileReader;
@class java_lang_StringBuilder;
@class java_io_PrintStream;
@class java_lang_System;
@class java_io_BufferedInputStream;
@class java_io_FileInputStream;
@class java_io_FileOutputStream;
@class java_lang_Object;
@class org_apertium_lttoolbox_process_FSTProcessor_GenerationMode;
@class org_apertium_lttoolbox_LTProc;
@class java_io_Writer;
@class java_lang_String;
@class java_io_InputStreamReader;
@class org_apertium_lttoolbox_process_FSTProcessor;
@class org_apertium_lttoolbox_process_State;
@class java_io_OutputStreamWriter;
@class java_lang_RuntimeException;
@class java_lang_Exception;
@class java_io_File;
@class java_io_OutputStream;
@class org_apertium_lttoolbox_MyGetOpt;
@class java_io_Reader;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_apertium_lttoolbox_LTProc : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
+ (java_lang_String*) _GET_PACKAGE_VERSION;
+ (void) _PUT_PACKAGE_VERSION: (java_lang_String*) v;
- (void) __init_org_apertium_lttoolbox_LTProc__;
+ (void) endProgram___java_lang_String :(java_lang_String*)n1;
+ (void) checkValidity___org_apertium_lttoolbox_process_FSTProcessor :(org_apertium_lttoolbox_process_FSTProcessor*)n1;
+ (void) main___java_lang_String_ARRAYTYPE :(XMLVMArray*)n1;
+ (java_io_Writer*) fout___java_lang_String :(java_lang_String*)n1;
+ (java_io_InputStream*) fopen___java_lang_String :(java_lang_String*)n1;
+ (java_io_Reader*) openReader___java_lang_String :(java_lang_String*)n1;

@end

