#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class org_apertium_lttoolbox_process_Node;
@class org_apertium_lttoolbox_process_Transition;
@class java_util_Map;
@class java_lang_Object;
@class java_lang_StringBuilder;
@class java_lang_String;
@class java_lang_Integer;
@class java_util_HashMap;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_apertium_lttoolbox_process_Node : java_lang_Object
{
@private java_util_Map* org_apertium_lttoolbox_process_Node_transitions;

}
+ (void) initialize;
- (id) init;
- (java_util_Map*) _GET_transitions;
- (void) _PUT_transitions: (java_util_Map*) v;
+ (int) _GET_FAST_BUT_REVERSE_ORDER;
+ (void) _PUT_FAST_BUT_REVERSE_ORDER: (int) v;
- (void) __init_org_apertium_lttoolbox_process_Node__;
- (void) initTransitions___int :(int)n1;
- (void) addTransition___int_int_org_apertium_lttoolbox_process_Node :(int)n1 :(int)n2 :(org_apertium_lttoolbox_process_Node*)n3;
- (java_lang_String*) toString__;

@end

