#import "xmlvm.h"
#import "org_apertium_lttoolbox_Getopt.h"

// For circular include:
@class java_lang_Object;
@class java_lang_String;
@class org_apertium_lttoolbox_MyGetOpt;
@class org_apertium_lttoolbox_Getopt;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_apertium_lttoolbox_MyGetOpt : org_apertium_lttoolbox_Getopt
{

}
+ (void) initialize;
- (id) init;
- (void) __init_org_apertium_lttoolbox_MyGetOpt___java_lang_String_ARRAYTYPE_java_lang_String :(XMLVMArray*)n1 :(java_lang_String*)n2;
- (int) getNextOption__;

@end

