#import "xmlvm.h"
#import "java_lang_Enum.h"

// For circular include:
@class java_lang_Object;
@class org_apertium_lttoolbox_process_FSTProcessor_GenerationMode;
@class java_lang_Class;
@class java_lang_String;
@class java_lang_Enum;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_apertium_lttoolbox_process_FSTProcessor_GenerationMode : java_lang_Enum
{

}
+ (void) initialize;
- (id) init;
+ (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) _GET_gm_clean;
+ (void) _PUT_gm_clean: (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) v;
+ (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) _GET_gm_unknown;
+ (void) _PUT_gm_unknown: (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) v;
+ (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) _GET_gm_all;
+ (void) _PUT_gm_all: (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) v;
+ (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) _GET_gm_tagged;
+ (void) _PUT_gm_tagged: (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) v;
+ (XMLVMArray*) _GET__VALUES;
+ (void) _PUT__VALUES: (XMLVMArray*) v;
+ (XMLVMArray*) values__;
+ (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) valueOf___java_lang_String :(java_lang_String*)n1;
- (void) __init_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode___java_lang_String_int :(java_lang_String*)n1 :(int)n2;
+ (void) __clinit_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode;

@end

