#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_lang_Object;
@class java_util_Vector;
@class java_util_List;
@class org_apertium_lttoolbox_transfer_MatchNode;
@class java_util_Collection;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_apertium_lttoolbox_transfer_MatchNode : java_lang_Object
{
@private java_util_List* org_apertium_lttoolbox_transfer_MatchNode_transitions;

}
+ (void) initialize;
- (id) init;
- (java_util_List*) _GET_transitions;
- (void) _PUT_transitions: (java_util_List*) v;
- (void) __init_org_apertium_lttoolbox_transfer_MatchNode__;
- (void) __init_org_apertium_lttoolbox_transfer_MatchNode___int :(int)n1;
- (void) __init_org_apertium_lttoolbox_transfer_MatchNode___org_apertium_lttoolbox_transfer_MatchNode :(org_apertium_lttoolbox_transfer_MatchNode*)n1;
- (void) addTransition___int_org_apertium_lttoolbox_transfer_MatchNode_int :(int)n1 :(org_apertium_lttoolbox_transfer_MatchNode*)n2 :(int)n3;

@end

