#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_io_FileOutputStream;
@class java_lang_Object;
@class java_io_Writer;
@class java_lang_String;
@class java_lang_StringBuilder;
@class java_io_PrintStream;
@class java_lang_System;
@class java_io_OutputStreamWriter;
@class org_apertium_lttoolbox_Expander;
@class java_lang_RuntimeException;
@class java_io_File;
@class org_apertium_lttoolbox_LTExpand;
@class java_io_OutputStream;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_apertium_lttoolbox_LTExpand : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
+ (java_lang_String*) _GET_PACKAGE_VERSION;
+ (void) _PUT_PACKAGE_VERSION: (java_lang_String*) v;
- (void) __init_org_apertium_lttoolbox_LTExpand__;
+ (void) endProgram___java_lang_String :(java_lang_String*)n1;
+ (void) main___java_lang_String_ARRAYTYPE :(XMLVMArray*)n1;
+ (java_io_Writer*) fwrite___java_lang_String :(java_lang_String*)n1;

@end

