#import "java_lang_Object.h"
#import "java_lang_String.h"

// Automatically generated by xmlvm2obj. Do not edit!


#import "org_apertium_lttoolbox_MyGetOpt.h"


@implementation org_apertium_lttoolbox_MyGetOpt;

+ (void) initialize
{
    if (strcmp(class_getName(self), "org_apertium_lttoolbox_MyGetOpt") == 0) {
    }
}

- (id) init
{
    if (self = [super init]) {
    }
    return self;
}

- (void) dealloc
{
    [super dealloc];
}

- (void) __init_org_apertium_lttoolbox_MyGetOpt___java_lang_String_ARRAYTYPE_java_lang_String :(XMLVMArray*)n1 :(java_lang_String*)n2
{
    XMLVMElem _stack[4];
    XMLVMElem _locals[3];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _locals[0].o = self;
    _locals[1].o = n1;
    _locals[2].o = n2;
    label0:;
    _stack[_sp++].o = _locals[0].o;
    _stack[_sp++].o = @"lttoolbox";
    _stack[_sp++].o = _locals[1].o;
    _stack[_sp++].o = _locals[2].o;
    _sp -= 4;
    [((super)) __init_org_apertium_lttoolbox_Getopt___java_lang_String_java_lang_String_ARRAYTYPE_java_lang_String:_stack[_sp + 1].o:_stack[_sp + 2].o:_stack[_sp + 3].o];
    label1:;
    [_pool release];
    return;
}


- (int) getNextOption__
{
    XMLVMElem _stack[1];
    XMLVMElem _locals[1];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _locals[0].o = self;
    label0:;
    _stack[_sp++].o = _locals[0].o;
    _sp -= 1;
    _op1.i = [((org_apertium_lttoolbox_MyGetOpt*) _stack[_sp].o) getopt__];
    _stack[_sp++].i = _op1.i;
    label1:;
    _op1.i = _stack[--_sp].i;
    [_pool release];
    return _op1.i;
}



@end

