#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_lang_Object;
@class org_apertium_lttoolbox_Pair;
@class java_lang_StringBuilder;
@class java_lang_String;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_apertium_lttoolbox_Pair : java_lang_Object
{
@private java_lang_Object* org_apertium_lttoolbox_Pair_first;
@private java_lang_Object* org_apertium_lttoolbox_Pair_second;

}
+ (void) initialize;
- (id) init;
- (java_lang_Object*) _GET_first;
- (void) _PUT_first: (java_lang_Object*) v;
- (java_lang_Object*) _GET_second;
- (void) _PUT_second: (java_lang_Object*) v;
- (void) __init_org_apertium_lttoolbox_Pair___java_lang_Object_java_lang_Object :(java_lang_Object*)n1 :(java_lang_Object*)n2;
- (java_lang_Object*) getFirst__;
- (void) setFirst___java_lang_Object :(java_lang_Object*)n1;
- (java_lang_Object*) getSecond__;
- (void) setSecond___java_lang_Object :(java_lang_Object*)n1;
- (java_lang_String*) toString__;

@end

