#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_lang_Object;
@class org_xml_sax_SAXParseException;
@class javax_xml_validation_Schema;
@class javax_xml_validation_SchemaFactory;
@class javax_xml_transform_Source;
@class java_net_MalformedURLException;
@class java_lang_StringBuilder;
@class java_lang_String;
@class java_io_PrintStream;
@class java_lang_System;
@class javax_xml_validation_Validator;
@class java_net_URL;
@class java_lang_Exception;
@class java_lang_Class;
@class javax_xml_transform_stream_StreamSource;
@class org_apertium_lttoolbox_LTValidate;
@class java_io_FileNotFoundException;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_apertium_lttoolbox_LTValidate : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
+ (java_lang_String*) _GET_PACKAGE_VERSION;
+ (void) _PUT_PACKAGE_VERSION: (java_lang_String*) v;
- (void) __init_org_apertium_lttoolbox_LTValidate__;
+ (void) usage__;
+ (int) validateDix___java_lang_String :(java_lang_String*)n1;
+ (int) validateAcx___java_lang_String :(java_lang_String*)n1;
+ (int) validateXmlSchema___java_net_URL_java_lang_String :(java_net_URL*)n1 :(java_lang_String*)n2;
+ (void) main___java_lang_String_ARRAYTYPE :(XMLVMArray*)n1;

@end

