#import "java_lang_Object.h"
#import "java_lang_Class.h"
#import "java_lang_String.h"

// Automatically generated by xmlvm2obj. Do not edit!


#import "org_apertium_lttoolbox_process_FSTProcessor_GenerationMode.h"

org_apertium_lttoolbox_process_FSTProcessor_GenerationMode* _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_clean;
org_apertium_lttoolbox_process_FSTProcessor_GenerationMode* _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_unknown;
org_apertium_lttoolbox_process_FSTProcessor_GenerationMode* _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_all;
org_apertium_lttoolbox_process_FSTProcessor_GenerationMode* _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_tagged;
XMLVMArray* _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode__VALUES;

@implementation org_apertium_lttoolbox_process_FSTProcessor_GenerationMode;

+ (void) initialize
{
    if (strcmp(class_getName(self), "org_apertium_lttoolbox_process_FSTProcessor_GenerationMode") == 0) {
        _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_clean = (id) [NSNull null];
        _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_unknown = (id) [NSNull null];
        _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_all = (id) [NSNull null];
        _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_tagged = (id) [NSNull null];
        _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode__VALUES = (id) [NSNull null];
        [org_apertium_lttoolbox_process_FSTProcessor_GenerationMode __clinit_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode];
    }
}

- (id) init
{
    if (self = [super init]) {
    }
    return self;
}

- (void) dealloc
{
    [super dealloc];
}

+ (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) _GET_gm_clean
{
    return [[_STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_clean retain] autorelease];
}

+ (void) _PUT_gm_clean: (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) v
{
    [v retain];
    [_STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_clean release];
    _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_clean = v;
}

+ (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) _GET_gm_unknown
{
    return [[_STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_unknown retain] autorelease];
}

+ (void) _PUT_gm_unknown: (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) v
{
    [v retain];
    [_STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_unknown release];
    _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_unknown = v;
}

+ (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) _GET_gm_all
{
    return [[_STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_all retain] autorelease];
}

+ (void) _PUT_gm_all: (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) v
{
    [v retain];
    [_STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_all release];
    _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_all = v;
}

+ (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) _GET_gm_tagged
{
    return [[_STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_tagged retain] autorelease];
}

+ (void) _PUT_gm_tagged: (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) v
{
    [v retain];
    [_STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_tagged release];
    _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode_gm_tagged = v;
}

+ (XMLVMArray*) _GET__VALUES
{
    return [[_STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode__VALUES retain] autorelease];
}

+ (void) _PUT__VALUES: (XMLVMArray*) v
{
    [v retain];
    [_STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode__VALUES release];
    _STATIC_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode__VALUES = v;
}

+ (XMLVMArray*) values__
{
    XMLVMElem _stack[1];
    XMLVMElem _locals[0];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _op1.o = [org_apertium_lttoolbox_process_FSTProcessor_GenerationMode _GET__VALUES];
    _stack[_sp++].o = _op1.o;
    _sp -= 1;
    _op1.o = [((java_lang_Object*) _stack[_sp].o) clone__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    [_op1.o retain];
    [_pool release];
    return _op1.o;
}


+ (org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) valueOf___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _stack[2];
    XMLVMElem _locals[1];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _locals[0].o = n1;
    label0:;
    _stack[_sp++].o = [org_apertium_lttoolbox_process_FSTProcessor_GenerationMode getClass__];
    _stack[_sp++].o = _locals[0].o;
    _sp -= 2;
    _op1.o = [java_lang_Enum valueOf___java_lang_Class_java_lang_String:_stack[_sp + 0].o:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    label1:;
    _op1.o = _stack[--_sp].o;
    [_op1.o retain];
    [_pool release];
    return _op1.o;
}


- (void) __init_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode___java_lang_String_int :(java_lang_String*)n1 :(int)n2
{
    XMLVMElem _stack[3];
    XMLVMElem _locals[3];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _locals[0].o = self;
    _locals[1].o = n1;
    _locals[2].i = n2;
    label0:;
    _stack[_sp++].o = _locals[0].o;
    _stack[_sp++].o = _locals[1].o;
    _op1.i = _locals[2].i;
    _stack[_sp++].i = _op1.i;
    _sp -= 3;
    [((super)) __init_java_lang_Enum___java_lang_String_int:_stack[_sp + 1].o:_stack[_sp + 2].i];
    label1:;
    [_pool release];
    return;
}


+ (void) __clinit_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode
{
    XMLVMElem _stack[4];
    XMLVMElem _locals[0];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _stack[_sp++].o = [[[org_apertium_lttoolbox_process_FSTProcessor_GenerationMode alloc] init] autorelease];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _stack[_sp++].o = @"gm_clean";
    _stack[_sp++].i = 0;
    _sp -= 3;
    [((org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) _stack[_sp].o) __init_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode___java_lang_String_int:_stack[_sp + 1].o:_stack[_sp + 2].i];
    _op1.o = _stack[--_sp].o;
    [org_apertium_lttoolbox_process_FSTProcessor_GenerationMode _PUT_gm_clean: _op1.o];
    _stack[_sp++].o = [[[org_apertium_lttoolbox_process_FSTProcessor_GenerationMode alloc] init] autorelease];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _stack[_sp++].o = @"gm_unknown";
    _stack[_sp++].i = 1;
    _sp -= 3;
    [((org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) _stack[_sp].o) __init_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode___java_lang_String_int:_stack[_sp + 1].o:_stack[_sp + 2].i];
    _op1.o = _stack[--_sp].o;
    [org_apertium_lttoolbox_process_FSTProcessor_GenerationMode _PUT_gm_unknown: _op1.o];
    _stack[_sp++].o = [[[org_apertium_lttoolbox_process_FSTProcessor_GenerationMode alloc] init] autorelease];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _stack[_sp++].o = @"gm_all";
    _stack[_sp++].i = 2;
    _sp -= 3;
    [((org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) _stack[_sp].o) __init_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode___java_lang_String_int:_stack[_sp + 1].o:_stack[_sp + 2].i];
    _op1.o = _stack[--_sp].o;
    [org_apertium_lttoolbox_process_FSTProcessor_GenerationMode _PUT_gm_all: _op1.o];
    _stack[_sp++].o = [[[org_apertium_lttoolbox_process_FSTProcessor_GenerationMode alloc] init] autorelease];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _stack[_sp++].o = @"gm_tagged";
    _stack[_sp++].i = 3;
    _sp -= 3;
    [((org_apertium_lttoolbox_process_FSTProcessor_GenerationMode*) _stack[_sp].o) __init_org_apertium_lttoolbox_process_FSTProcessor_GenerationMode___java_lang_String_int:_stack[_sp + 1].o:_stack[_sp + 2].i];
    _op1.o = _stack[--_sp].o;
    [org_apertium_lttoolbox_process_FSTProcessor_GenerationMode _PUT_gm_tagged: _op1.o];
    _stack[_sp++].i = 4;
    _op1.i = _stack[--_sp].i;
    _stack[_sp++].o = [XMLVMArray createSingleDimensionWithType:0 andSize:_op1.i];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _stack[_sp++].i = 0;
    _op1.o = [org_apertium_lttoolbox_process_FSTProcessor_GenerationMode _GET_gm_clean];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    _op2.i = _stack[--_sp].i;
    _op3.o = _stack[--_sp].o;
    [_op3.o replaceObjectAtIndex: _op2.i withObject: _op1.o];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _stack[_sp++].i = 1;
    _op1.o = [org_apertium_lttoolbox_process_FSTProcessor_GenerationMode _GET_gm_unknown];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    _op2.i = _stack[--_sp].i;
    _op3.o = _stack[--_sp].o;
    [_op3.o replaceObjectAtIndex: _op2.i withObject: _op1.o];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _stack[_sp++].i = 2;
    _op1.o = [org_apertium_lttoolbox_process_FSTProcessor_GenerationMode _GET_gm_all];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    _op2.i = _stack[--_sp].i;
    _op3.o = _stack[--_sp].o;
    [_op3.o replaceObjectAtIndex: _op2.i withObject: _op1.o];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _stack[_sp++].i = 3;
    _op1.o = [org_apertium_lttoolbox_process_FSTProcessor_GenerationMode _GET_gm_tagged];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    _op2.i = _stack[--_sp].i;
    _op3.o = _stack[--_sp].o;
    [_op3.o replaceObjectAtIndex: _op2.i withObject: _op1.o];
    _op1.o = _stack[--_sp].o;
    [org_apertium_lttoolbox_process_FSTProcessor_GenerationMode _PUT__VALUES: _op1.o];
    [_pool release];
    return;
}



@end

