#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class javax_xml_stream_XMLStreamReader;
@class java_lang_Object;
@class java_lang_String;
@class java_lang_StringBuilder;
@class org_apertium_lttoolbox_compile_XMLPrint;
@class java_io_PrintStream;
@class java_lang_System;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_apertium_lttoolbox_compile_XMLPrint : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
- (void) __init_org_apertium_lttoolbox_compile_XMLPrint__;
+ (void) printNEvent___javax_xml_stream_XMLStreamReader_int :(javax_xml_stream_XMLStreamReader*)n1 :(int)n2;
+ (void) printEvent___javax_xml_stream_XMLStreamReader :(javax_xml_stream_XMLStreamReader*)n1;
+ (java_lang_String*) getEventTypeString___int :(int)n1;
+ (void) printName___javax_xml_stream_XMLStreamReader :(javax_xml_stream_XMLStreamReader*)n1;
+ (void) printName___java_lang_String_java_lang_String_java_lang_String :(java_lang_String*)n1 :(java_lang_String*)n2 :(java_lang_String*)n3;
+ (void) printAttributes___javax_xml_stream_XMLStreamReader :(javax_xml_stream_XMLStreamReader*)n1;
+ (void) printAttribute___javax_xml_stream_XMLStreamReader_int :(javax_xml_stream_XMLStreamReader*)n1 :(int)n2;
+ (void) printNamespaces___javax_xml_stream_XMLStreamReader :(javax_xml_stream_XMLStreamReader*)n1;
+ (void) printNamespace___javax_xml_stream_XMLStreamReader_int :(javax_xml_stream_XMLStreamReader*)n1 :(int)n2;

@end

