#import "xmlvm.h"
#import "java_util_ArrayList.h"

// For circular include:
@class java_util_ArrayList;
@class java_lang_Object;
@class org_apertium_lttoolbox_Expander_EntList;
@class java_util_Collection;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_apertium_lttoolbox_Expander_EntList : java_util_ArrayList
{

}
+ (void) initialize;
- (id) init;
- (void) __init_org_apertium_lttoolbox_Expander_EntList__;
- (void) __init_org_apertium_lttoolbox_Expander_EntList___java_util_Collection :(java_util_Collection*)n1;

@end

