#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class org_apertium_lttoolbox_process_Node;
@class org_apertium_lttoolbox_process_Transition;
@class java_lang_Object;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_apertium_lttoolbox_process_Transition : java_lang_Object
{
@private int org_apertium_lttoolbox_process_Transition_output_symbol;
@private org_apertium_lttoolbox_process_Node* org_apertium_lttoolbox_process_Transition_dest;
@private org_apertium_lttoolbox_process_Transition* org_apertium_lttoolbox_process_Transition_next;

}
+ (void) initialize;
- (id) init;
- (int) _GET_output_symbol;
- (void) _PUT_output_symbol: (int) v;
- (org_apertium_lttoolbox_process_Node*) _GET_dest;
- (void) _PUT_dest: (org_apertium_lttoolbox_process_Node*) v;
- (org_apertium_lttoolbox_process_Transition*) _GET_next;
- (void) _PUT_next: (org_apertium_lttoolbox_process_Transition*) v;
- (void) __init_org_apertium_lttoolbox_process_Transition__;

@end

