#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_lang_Object;
@class org_apertium_lttoolbox_LTProc;
@class org_apertium_lttoolbox_LTComp;
@class org_apertium_lttoolbox_LTToolbox;
@class java_lang_String;
@class java_lang_StringBuilder;
@class java_io_PrintStream;
@class java_lang_System;
@class java_lang_CharSequence;
@class org_apertium_lttoolbox_LTExpand;
@class java_util_Arrays;
@class org_apertium_lttoolbox_LTValidate;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_apertium_lttoolbox_LTToolbox : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
- (void) __init_org_apertium_lttoolbox_LTToolbox__;
+ (void) showHelp___java_lang_String :(java_lang_String*)n1;
+ (void) main___java_lang_String_ARRAYTYPE :(XMLVMArray*)n1;

@end

