#import "java_io_InputStream.h"
#import "android_text_Spanned.h"
#import "java_net_URLConnection.h"
#import "java_io_BufferedReader.h"
#import "android_text_Html.h"
#import "java_lang_StringBuilder.h"
#import "java_lang_String.h"
#import "java_net_MalformedURLException.h"
#import "java_io_PrintStream.h"
#import "java_io_InputStreamReader.h"
#import "java_lang_System.h"
#import "java_io_IOException.h"
#import "java_net_URLEncoder.h"
#import "java_net_URL.h"
#import "java_io_Reader.h"

// Automatically generated by xmlvm2obj. Do not edit!


#import "engine_utils_ApertiumWS.h"


@implementation engine_utils_ApertiumWS;

+ (void) initialize
{
    if (strcmp(class_getName(self), "engine_utils_ApertiumWS") == 0) {
    }
}

- (id) init
{
    if (self = [super init]) {
        engine_utils_ApertiumWS_sl = (id) [NSNull null];
        engine_utils_ApertiumWS_tl = (id) [NSNull null];
        engine_utils_ApertiumWS_text = (id) [NSNull null];
        engine_utils_ApertiumWS_translation = (id) [NSNull null];
    }
    return self;
}

- (void) dealloc
{
    [engine_utils_ApertiumWS_sl release];
    [engine_utils_ApertiumWS_tl release];
    [engine_utils_ApertiumWS_text release];
    [engine_utils_ApertiumWS_translation release];
    [super dealloc];
}

- (java_lang_String*) _GET_sl
{
    return [[engine_utils_ApertiumWS_sl retain] autorelease];
}

- (void) _PUT_sl: (java_lang_String*) v
{
    [v retain];
    [engine_utils_ApertiumWS_sl release];
    engine_utils_ApertiumWS_sl = v;
}

- (java_lang_String*) _GET_tl
{
    return [[engine_utils_ApertiumWS_tl retain] autorelease];
}

- (void) _PUT_tl: (java_lang_String*) v
{
    [v retain];
    [engine_utils_ApertiumWS_tl release];
    engine_utils_ApertiumWS_tl = v;
}

- (java_lang_String*) _GET_text
{
    return [[engine_utils_ApertiumWS_text retain] autorelease];
}

- (void) _PUT_text: (java_lang_String*) v
{
    [v retain];
    [engine_utils_ApertiumWS_text release];
    engine_utils_ApertiumWS_text = v;
}

- (java_lang_String*) _GET_translation
{
    return [[engine_utils_ApertiumWS_translation retain] autorelease];
}

- (void) _PUT_translation: (java_lang_String*) v
{
    [v retain];
    [engine_utils_ApertiumWS_translation release];
    engine_utils_ApertiumWS_translation = v;
}

- (int) _GET_markUnknown
{
    return engine_utils_ApertiumWS_markUnknown;
}

- (void) _PUT_markUnknown: (int) v
{
    engine_utils_ApertiumWS_markUnknown = v;
}

- (void) __init_engine_utils_ApertiumWS___java_lang_String_java_lang_String_java_lang_String :(java_lang_String*)n1 :(java_lang_String*)n2 :(java_lang_String*)n3
{
    XMLVMElem _stack[2];
    XMLVMElem _locals[4];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _locals[0].o = self;
    _locals[1].o = n1;
    _locals[2].o = n2;
    _locals[3].o = n3;
    label0:;
    _stack[_sp++].o = _locals[0].o;
    _sp -= 1;
    [((super)) __init_java_lang_Object__];
    _stack[_sp++].o = _locals[0].o;
    _stack[_sp++].o = _locals[1].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = _stack[--_sp].o;
    [((engine_utils_ApertiumWS*) _op2.o) _PUT_sl: _op1.o];
    _stack[_sp++].o = _locals[0].o;
    _stack[_sp++].o = _locals[2].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = _stack[--_sp].o;
    [((engine_utils_ApertiumWS*) _op2.o) _PUT_tl: _op1.o];
    _stack[_sp++].o = _locals[0].o;
    _stack[_sp++].o = _locals[3].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = _stack[--_sp].o;
    [((engine_utils_ApertiumWS*) _op2.o) _PUT_text: _op1.o];
    _stack[_sp++].o = _locals[0].o;
    _stack[_sp++].i = 0;
    _op1.i = _stack[--_sp].i;
    _op2.o = _stack[--_sp].o;
    [((engine_utils_ApertiumWS*) _op2.o) _PUT_markUnknown: _op1.i];
    label1:;
    [_pool release];
    return;
}


- (void) setMarkUnknown___boolean :(int)n1
{
    XMLVMElem _stack[2];
    XMLVMElem _locals[2];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _locals[0].o = self;
    _locals[1].i = n1;
    label0:;
    _stack[_sp++].o = _locals[0].o;
    _op1.i = _locals[1].i;
    _stack[_sp++].i = _op1.i;
    _op1.i = _stack[--_sp].i;
    _op2.o = _stack[--_sp].o;
    [((engine_utils_ApertiumWS*) _op2.o) _PUT_markUnknown: _op1.i];
    label1:;
    [_pool release];
    return;
}


- (int) isMarkUnknown__
{
    XMLVMElem _stack[1];
    XMLVMElem _locals[1];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _locals[0].o = self;
    label0:;
    _stack[_sp++].o = _locals[0].o;
    _op1.o = _stack[--_sp].o;
    _op2.i = [((engine_utils_ApertiumWS*) _op1.o)  _GET_markUnknown];
    _stack[_sp++].i = _op2.i;
    label1:;
    _op1.i = _stack[--_sp].i;
    [_pool release];
    return _op1.i;
}


- (java_lang_String*) translate__
{
    XMLVMElem _stack[4];
    XMLVMElem _locals[9];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _locals[0].o = self;
    label3:;
    _stack[_sp++].o = [NSNull null];
    _op1.o = _stack[--_sp].o;
    _locals[2].o = _op1.o;
    label7:;
    _stack[_sp++].o = [NSNull null];
    _op1.o = _stack[--_sp].o;
    _locals[3].o = _op1.o;
    label9:;
    _stack[_sp++].o = [NSNull null];
    _op1.o = _stack[--_sp].o;
    _locals[4].o = _op1.o;
    label11:;
    _stack[_sp++].o = [NSNull null];
    _op1.o = _stack[--_sp].o;
    _locals[5].o = _op1.o;
    label13:;
    @try {
    @try {
    _stack[_sp++].o = _locals[0].o;
    _stack[_sp++].o = _locals[0].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = [((engine_utils_ApertiumWS*) _op1.o)  _GET_text];
    _stack[_sp++].o = _op2.o;
    _stack[_sp++].o = @"UTF-8";
    _sp -= 2;
    _op1.o = [java_net_URLEncoder encode___java_lang_String_java_lang_String:_stack[_sp + 0].o:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    _op2.o = _stack[--_sp].o;
    [((engine_utils_ApertiumWS*) _op2.o) _PUT_text: _op1.o];
    _stack[_sp++].o = @"0";
    _op1.o = _stack[--_sp].o;
    _locals[6].o = _op1.o;
    label19:;
    _stack[_sp++].o = _locals[0].o;
    _sp -= 1;
    _op1.i = [((engine_utils_ApertiumWS*) _stack[_sp].o) isMarkUnknown__];
    _stack[_sp++].i = _op1.i;
    _op1.i = _stack[--_sp].i;
    if (_op1.i == 0) goto label0;
    _stack[_sp++].o = @"1";
    _op1.o = _stack[--_sp].o;
    _locals[6].o = _op1.o;
    label0:;
    _stack[_sp++].o = [[[java_lang_StringBuilder alloc] init] autorelease];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _sp -= 1;
    [((java_lang_StringBuilder*) _stack[_sp].o) __init_java_lang_StringBuilder__];
    _stack[_sp++].o = @"http://xixona.dlsi.ua.es/webservice/ws.php?mark=";
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = _locals[6].o;
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = @"&mode=";
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = _locals[0].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = [((engine_utils_ApertiumWS*) _op1.o)  _GET_sl];
    _stack[_sp++].o = _op2.o;
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = @"-";
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = _locals[0].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = [((engine_utils_ApertiumWS*) _op1.o)  _GET_tl];
    _stack[_sp++].o = _op2.o;
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = @"&text=";
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = _locals[0].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = [((engine_utils_ApertiumWS*) _op1.o)  _GET_text];
    _stack[_sp++].o = _op2.o;
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = @"";
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 1;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) toString__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    _locals[7].o = _op1.o;
    label21:;
    _stack[_sp++].o = [[[java_net_URL alloc] init] autorelease];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _stack[_sp++].o = _locals[7].o;
    _sp -= 2;
    [((java_net_URL*) _stack[_sp].o) __init_java_net_URL___java_lang_String:_stack[_sp + 1].o];
    _op1.o = _stack[--_sp].o;
    _locals[2].o = _op1.o;
    _stack[_sp++].o = _locals[2].o;
    _sp -= 1;
    _op1.o = [((java_net_URL*) _stack[_sp].o) openConnection__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    _locals[3].o = _op1.o;
    _stack[_sp++].o = [[[java_io_InputStreamReader alloc] init] autorelease];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _stack[_sp++].o = _locals[3].o;
    _sp -= 1;
    _op1.o = [((java_net_URLConnection*) _stack[_sp].o) getInputStream__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 2;
    [((java_io_InputStreamReader*) _stack[_sp].o) __init_java_io_InputStreamReader___java_io_InputStream:_stack[_sp + 1].o];
    _op1.o = _stack[--_sp].o;
    _locals[4].o = _op1.o;
    _stack[_sp++].o = [[[java_io_BufferedReader alloc] init] autorelease];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _stack[_sp++].o = _locals[4].o;
    _sp -= 2;
    [((java_io_BufferedReader*) _stack[_sp].o) __init_java_io_BufferedReader___java_io_Reader:_stack[_sp + 1].o];
    _op1.o = _stack[--_sp].o;
    _locals[5].o = _op1.o;
    _stack[_sp++].o = @"";
    _op1.o = _stack[--_sp].o;
    _locals[8].o = _op1.o;
    label2:;
    _stack[_sp++].o = _locals[5].o;
    _sp -= 1;
    _op1.o = [((java_io_BufferedReader*) _stack[_sp].o) readLine__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    _locals[1].o = _op1.o;
    label5:;
    _stack[_sp++].o = _locals[1].o;
    _op1.o = _stack[--_sp].o;
    if (_op1.o == [NSNull null]) goto label1;
    _stack[_sp++].o = [[[java_lang_StringBuilder alloc] init] autorelease];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _sp -= 1;
    [((java_lang_StringBuilder*) _stack[_sp].o) __init_java_lang_StringBuilder__];
    _stack[_sp++].o = _locals[8].o;
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = _locals[1].o;
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 1;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) toString__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    _locals[8].o = _op1.o;
    goto label2;
    label1:;
    _stack[_sp++].o = _locals[0].o;
    _stack[_sp++].o = _locals[8].o;
    _sp -= 2;
    [((engine_utils_ApertiumWS*) _stack[_sp].o) setTranslation___java_lang_String:_stack[_sp + 1].o];
    _stack[_sp++].o = _locals[0].o;
    _stack[_sp++].o = _locals[0].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = [((engine_utils_ApertiumWS*) _op1.o)  _GET_translation];
    _stack[_sp++].o = _op2.o;
    _stack[_sp++].o = @"<libtranslate>";
    _stack[_sp++].o = @"";
    _sp -= 3;
    _op1.o = [((java_lang_String*) _stack[_sp].o) replaceAll___java_lang_String_java_lang_String:_stack[_sp + 1].o:_stack[_sp + 2].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    _op2.o = _stack[--_sp].o;
    [((engine_utils_ApertiumWS*) _op2.o) _PUT_translation: _op1.o];
    _stack[_sp++].o = _locals[0].o;
    _stack[_sp++].o = _locals[0].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = [((engine_utils_ApertiumWS*) _op1.o)  _GET_translation];
    _stack[_sp++].o = _op2.o;
    _stack[_sp++].o = @"</libtranslate>";
    _stack[_sp++].o = @"";
    _sp -= 3;
    _op1.o = [((java_lang_String*) _stack[_sp].o) replaceAll___java_lang_String_java_lang_String:_stack[_sp + 1].o:_stack[_sp + 2].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    _op2.o = _stack[--_sp].o;
    [((engine_utils_ApertiumWS*) _op2.o) _PUT_translation: _op1.o];
    _stack[_sp++].o = _locals[0].o;
    _stack[_sp++].o = _locals[0].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = [((engine_utils_ApertiumWS*) _op1.o)  _GET_translation];
    _stack[_sp++].o = _op2.o;
    _sp -= 1;
    _op1.o = [android_text_Html fromHtml___java_lang_String:_stack[_sp + 0].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 1;
    _op1.o = [((java_lang_Object*) _stack[_sp].o) toString__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    _op2.o = _stack[--_sp].o;
    [((engine_utils_ApertiumWS*) _op2.o) _PUT_translation: _op1.o];
    _stack[_sp++].o = _locals[0].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = [((engine_utils_ApertiumWS*) _op1.o)  _GET_translation];
    _stack[_sp++].o = _op2.o;
    } @catch (java_net_MalformedURLException* _ex) {
        _stack[_sp++].o = _ex;
        goto label20;
    }
    } @catch (java_io_IOException* _ex) {
        _stack[_sp++].o = _ex;
        goto label16;
    }
    _op1.o = _stack[--_sp].o;
    [_op1.o retain];
    [_pool release];
    return _op1.o;
    label20:;
    _op1.o = _stack[--_sp].o;
    _locals[6].o = _op1.o;
    label15:;
    _op1.o = [java_lang_System _GET_out];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = [[[java_lang_StringBuilder alloc] init] autorelease];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _sp -= 1;
    [((java_lang_StringBuilder*) _stack[_sp].o) __init_java_lang_StringBuilder__];
    _stack[_sp++].o = @"Please check the URL:";
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = _locals[6].o;
    _sp -= 1;
    _op1.o = [((java_net_MalformedURLException*) _stack[_sp].o) toString__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 1;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) toString__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 2;
    [((java_io_PrintStream*) _stack[_sp].o) println___java_lang_String:_stack[_sp + 1].o];
    _stack[_sp++].o = _locals[6].o;
    _sp -= 1;
    _op1.o = [((java_net_MalformedURLException*) _stack[_sp].o) toString__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _op1.o = _stack[--_sp].o;
    [_op1.o retain];
    [_pool release];
    return _op1.o;
    label16:;
    _op1.o = _stack[--_sp].o;
    _locals[6].o = _op1.o;
    label17:;
    _op1.o = [java_lang_System _GET_out];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = [[[java_lang_StringBuilder alloc] init] autorelease];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _sp -= 1;
    [((java_lang_StringBuilder*) _stack[_sp].o) __init_java_lang_StringBuilder__];
    _stack[_sp++].o = @"Can't read  from the Internet: ";
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = _locals[6].o;
    _sp -= 1;
    _op1.o = [((java_io_IOException*) _stack[_sp].o) toString__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 1;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) toString__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 2;
    [((java_io_PrintStream*) _stack[_sp].o) println___java_lang_String:_stack[_sp + 1].o];
    _stack[_sp++].o = [[[java_lang_StringBuilder alloc] init] autorelease];
    _op1 = _stack[_sp - 1];
    _stack[_sp++] = _op1;
    _sp -= 1;
    [((java_lang_StringBuilder*) _stack[_sp].o) __init_java_lang_StringBuilder__];
    _stack[_sp++].o = _locals[6].o;
    _sp -= 1;
    _op1.o = [((java_io_IOException*) _stack[_sp].o) toString__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = @"/ ";
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _stack[_sp++].o = _locals[6].o;
    _sp -= 1;
    _op1.o = [((java_io_IOException*) _stack[_sp].o) getMessage__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 2;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) append___java_lang_String:_stack[_sp + 1].o];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    _sp -= 1;
    _op1.o = [((java_lang_StringBuilder*) _stack[_sp].o) toString__];
    [_op1.o autorelease];
    _stack[_sp++].o = _op1.o;
    label4:;
    _op1.o = _stack[--_sp].o;
    [_op1.o retain];
    [_pool release];
    return _op1.o;
}


- (java_lang_String*) getTranslation__
{
    XMLVMElem _stack[1];
    XMLVMElem _locals[1];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _locals[0].o = self;
    label0:;
    _stack[_sp++].o = _locals[0].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = [((engine_utils_ApertiumWS*) _op1.o)  _GET_translation];
    _stack[_sp++].o = _op2.o;
    label1:;
    _op1.o = _stack[--_sp].o;
    [_op1.o retain];
    [_pool release];
    return _op1.o;
}


- (void) setTranslation___java_lang_String :(java_lang_String*)n1
{
    XMLVMElem _stack[2];
    XMLVMElem _locals[2];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _locals[0].o = self;
    _locals[1].o = n1;
    label0:;
    _stack[_sp++].o = _locals[0].o;
    _stack[_sp++].o = _locals[1].o;
    _op1.o = _stack[--_sp].o;
    _op2.o = _stack[--_sp].o;
    [((engine_utils_ApertiumWS*) _op2.o) _PUT_translation: _op1.o];
    label1:;
    [_pool release];
    return;
}



@end

