#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class org_me_apertium_R_attr;
@class java_lang_Object;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_me_apertium_R_attr : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
- (void) __init_org_me_apertium_R_attr__;

@end

