#import "xmlvm.h"
#import "java_lang_Object.h"
#import "android_widget_CompoundButton_OnCheckedChangeListener.h"

// For circular include:
@class org_me_apertium_MainActivity_1;
@class android_widget_CompoundButton;
@class java_lang_Object;
@class android_widget_CompoundButton_OnCheckedChangeListener;
@class org_me_apertium_MainActivity;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_me_apertium_MainActivity_1 : java_lang_Object <android_widget_CompoundButton_OnCheckedChangeListener>
{
@private org_me_apertium_MainActivity* org_me_apertium_MainActivity_1_this_0;

}
+ (void) initialize;
- (id) init;
- (org_me_apertium_MainActivity*) _GET_this_0;
- (void) _PUT_this_0: (org_me_apertium_MainActivity*) v;
- (void) __init_org_me_apertium_MainActivity_1___org_me_apertium_MainActivity :(org_me_apertium_MainActivity*)n1;
- (void) onCheckedChanged___android_widget_CompoundButton_boolean :(android_widget_CompoundButton*)n1 :(int)n2;

@end

