
// Automatically generated by xmlvm2obj. Do not edit!


#import "org_me_apertium_R_id.h"

int _STATIC_org_me_apertium_R_id_langpairs = 2131099648;
int _STATIC_org_me_apertium_R_id_markUnknown = 2131099650;
int _STATIC_org_me_apertium_R_id_sourceText = 2131099649;
int _STATIC_org_me_apertium_R_id_translateButton = 2131099651;
int _STATIC_org_me_apertium_R_id_translationText = 2131099652;

@implementation org_me_apertium_R_id;

+ (void) initialize
{
    if (strcmp(class_getName(self), "org_me_apertium_R_id") == 0) {
    }
}

- (id) init
{
    if (self = [super init]) {
    }
    return self;
}

- (void) dealloc
{
    [super dealloc];
}

+ (int) _GET_langpairs
{
    return _STATIC_org_me_apertium_R_id_langpairs;
}

+ (void) _PUT_langpairs: (int) v
{
    _STATIC_org_me_apertium_R_id_langpairs = v;
}

+ (int) _GET_markUnknown
{
    return _STATIC_org_me_apertium_R_id_markUnknown;
}

+ (void) _PUT_markUnknown: (int) v
{
    _STATIC_org_me_apertium_R_id_markUnknown = v;
}

+ (int) _GET_sourceText
{
    return _STATIC_org_me_apertium_R_id_sourceText;
}

+ (void) _PUT_sourceText: (int) v
{
    _STATIC_org_me_apertium_R_id_sourceText = v;
}

+ (int) _GET_translateButton
{
    return _STATIC_org_me_apertium_R_id_translateButton;
}

+ (void) _PUT_translateButton: (int) v
{
    _STATIC_org_me_apertium_R_id_translateButton = v;
}

+ (int) _GET_translationText
{
    return _STATIC_org_me_apertium_R_id_translationText;
}

+ (void) _PUT_translationText: (int) v
{
    _STATIC_org_me_apertium_R_id_translationText = v;
}

- (void) __init_org_me_apertium_R_id__
{
    XMLVMElem _stack[1];
    XMLVMElem _locals[1];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _locals[0].o = self;
    label0:;
    _stack[_sp++].o = _locals[0].o;
    _sp -= 1;
    [((super)) __init_java_lang_Object__];
    label1:;
    [_pool release];
    return;
}



@end

