#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_lang_Object;
@class org_me_apertium_R_id;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_me_apertium_R_id : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
+ (int) _GET_langpairs;
+ (void) _PUT_langpairs: (int) v;
+ (int) _GET_markUnknown;
+ (void) _PUT_markUnknown: (int) v;
+ (int) _GET_sourceText;
+ (void) _PUT_sourceText: (int) v;
+ (int) _GET_translateButton;
+ (void) _PUT_translateButton: (int) v;
+ (int) _GET_translationText;
+ (void) _PUT_translationText: (int) v;
- (void) __init_org_me_apertium_R_id__;

@end

