#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_lang_Object;
@class org_me_apertium_R_array;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_me_apertium_R_array : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
+ (int) _GET_language_codes;
+ (void) _PUT_language_codes: (int) v;
+ (int) _GET_language_pairs;
+ (void) _PUT_language_pairs: (int) v;
- (void) __init_org_me_apertium_R_array__;

@end

