
// Automatically generated by xmlvm2obj. Do not edit!


#import "org_me_apertium_R_string.h"

int _STATIC_org_me_apertium_R_string_app_name = 2130968576;

@implementation org_me_apertium_R_string;

+ (void) initialize
{
    if (strcmp(class_getName(self), "org_me_apertium_R_string") == 0) {
    }
}

- (id) init
{
    if (self = [super init]) {
    }
    return self;
}

- (void) dealloc
{
    [super dealloc];
}

+ (int) _GET_app_name
{
    return _STATIC_org_me_apertium_R_string_app_name;
}

+ (void) _PUT_app_name: (int) v
{
    _STATIC_org_me_apertium_R_string_app_name = v;
}

- (void) __init_org_me_apertium_R_string__
{
    XMLVMElem _stack[1];
    XMLVMElem _locals[1];
    int _sp = 0;
    XMLVMElem _op1, _op2, _op3;
    NSAutoreleasePool* _pool = [[NSAutoreleasePool alloc] init];
    _locals[0].o = self;
    label0:;
    _stack[_sp++].o = _locals[0].o;
    _sp -= 1;
    [((super)) __init_java_lang_Object__];
    label1:;
    [_pool release];
    return;
}



@end

