#import "xmlvm.h"
#import "java_lang_Object.h"
#import "android_view_View_OnClickListener.h"

// For circular include:
@class org_me_apertium_MainActivity_2;
@class android_view_View_OnClickListener;
@class java_lang_Object;
@class java_lang_Exception;
@class java_lang_String;
@class android_view_View;
@class java_lang_ArrayIndexOutOfBoundsException;
@class org_me_apertium_MainActivity;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface org_me_apertium_MainActivity_2 : java_lang_Object <android_view_View_OnClickListener>
{
@private org_me_apertium_MainActivity* org_me_apertium_MainActivity_2_this_0;

}
+ (void) initialize;
- (id) init;
- (org_me_apertium_MainActivity*) _GET_this_0;
- (void) _PUT_this_0: (org_me_apertium_MainActivity*) v;
- (void) __init_org_me_apertium_MainActivity_2___org_me_apertium_MainActivity :(org_me_apertium_MainActivity*)n1;
- (void) onClick___android_view_View :(android_view_View*)n1;

@end

