.TH desman 1 "18 octobre 2012" "Bernard Chardonneau" "Apertium dé-formateur"
.SH NOM
desman - Dé-formateur pour les pages de man. Cette application est un outil
du traducteur
.B apertium 
.SH SYNTAXE
.B desman
[ <fichier_d'entrée> [ <fichier_de_sortie> ] ]

.B desman
\- <fichier_de_sortie>
.SH DESCRIPTION
.TP
.BR desman 
est un outil de formatage pour les pages de man. Les données doivent être
passées à cet outil avant d'être "pipées" à apertium (utilisé avec l'option
.I -f none
Après ça,
.I reman
ou tout autre re-formateur équivalent doit être utilisé pour supprimer les
[ ] et \\ insérés par desman .
.SH OPTIONS
.TP
.B \-
peut être utilisé à la place d'un <fichier_d'entrée> lorsque l'entrée standard
est utilisée (via un pipe), alors que la sortie est écrite dans un fichier.
.SH EXEMPLES
cat desman.1 | desman | apertium -f none fr-es | reman

desman desman.1 | apertium -f none fr-es | reman
.SH VOIR AUSSI
desmnemo(1), reman(1), apertium-man(1), apertium(1).
.SH AUTEUR
Bernard Chardonneau  <bechapertium@free.fr>
